# Generated by Django 5.1.7 on 2026-04-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre del campo')),
                ('field_type', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('date', 'Fecha'), ('select', 'Selección'), ('checkbox', 'Casilla de verificación')], max_length=50, verbose_name='Tipo de dato')),
                ('options', models.JSONField(blank=True, null=True, verbose_name='Opciones del select separadas por una coma (,)')),
            ],
        ),
        migrations.CreateModel(
            name='MetadataSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre del esquema')),
                ('fields', models.ManyToManyField(related_name='schema_fields', to='metadata.metadatafield', verbose_name='Campos del esquema')),
            ],
        ),
    ]
