# Generated by Django 5.1.7 on 2026-04-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Correo Electrónico')),
                ('username', models.CharField(max_length=40, verbose_name='Nombre de usuario')),
                ('gender', models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO'), ('PREFIERO NO DECIRLO', 'PREFIERO NO DECIRLO')], default='PREFIERO NO DECIRLO', max_length=20, null=True, verbose_name='Género')),
                ('avatar', models.ImageField(blank=True, default='avatars/no-gender.png', null=True, upload_to='avatars')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificados/', verbose_name='certificado digital')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='user_groups', to='auth.group', verbose_name='Grupos')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
