# Generated by Django 5.1.7 on 2026-04-18 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Nombre del modulo')),
                ('icon', models.CharField(max_length=60, unique=True, verbose_name='Ícono del modulo')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
            ],
        ),
        migrations.CreateModel(
            name='SubModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Nombre del modulo')),
                ('url_name', models.CharField(max_length=100, unique=True, verbose_name='URL')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.module', verbose_name='Módulo')),
            ],
        ),
    ]
