# Generated by Django 5.1.7 on 2026-04-18 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro', models.CharField(default='BAUTIZO', max_length=200, verbose_name='Tipo de libro a digitalizar')),
                ('seq_value', models.BigIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre - identificador')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Documento')),
                ('file2', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Documento 2')),
                ('document_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='Acta PDF')),
                ('metadata_values', models.JSONField(blank=True, default=dict, null=True)),
                ('indexado', models.BooleanField(blank=True, default=False, null=True)),
                ('metadata_schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='metadata.metadataschema', verbose_name='Esquema de Metadatos')),
            ],
        ),
        migrations.CreateModel(
            name='TextoParametrizable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantilla_texto', models.TextField(verbose_name='Plantilla de Texto')),
                ('plantilla_pdf', models.JSONField(blank=True, null=True, verbose_name='Plantilla PDF Parametrizable')),
                ('schema', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='metadata.metadataschema', verbose_name='Esquema de Metadatos')),
            ],
            options={
                'verbose_name': 'Texto Parametrizable',
                'verbose_name_plural': 'Textos Parametrizables',
            },
        ),
    ]
