# Generated by Django 5.1.7 on 2026-04-18 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': [('index_document', 'Can index documents'), ('send_document', 'Can send documents via email'), ('sign_document', 'Can sign documents electronically')]},
        ),
        migrations.AlterModelOptions(
            name='documentsequence',
            options={'permissions': [('manage_sequences', 'Can manage document sequences')]},
        ),
        migrations.AlterModelOptions(
            name='textoparametrizable',
            options={'permissions': [('manage_pdf_templates', 'Can manage PDF templates'), ('manage_textos_parametrizables', 'Can manage parameterizable texts')], 'verbose_name': 'Texto Parametrizable', 'verbose_name_plural': 'Textos Parametrizables'},
        ),
    ]
