# Generated by Django 5.1.7 on 2026-04-18 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0002_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={},
        ),
        migrations.AlterModelOptions(
            name='documentsequence',
            options={},
        ),
        migrations.AlterModelOptions(
            name='textoparametrizable',
            options={'verbose_name': 'Texto Parametrizable', 'verbose_name_plural': 'Textos Parametrizables'},
        ),
    ]
