# Generated by Django 5.1.7 on 2026-04-18 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0003_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': [('index_document', 'Puede indexar documentos'), ('send_document', 'Puede enviar documentos por correo'), ('sign_document', 'Puede firmar documentos')]},
        ),
        migrations.AlterModelOptions(
            name='documentsequence',
            options={'permissions': [('manage_sequences', 'Puede gestionar secuencias de documentos')]},
        ),
        migrations.AlterModelOptions(
            name='textoparametrizable',
            options={'permissions': [('manage_pdf_templates', 'Puede gestionar plantillas PDF'), ('manage_textos_parametrizables', 'Puede gestionar textos parametrizables')], 'verbose_name': 'Texto Parametrizable', 'verbose_name_plural': 'Textos Parametrizables'},
        ),
    ]
